### ISSUE TITLE
QGC crashes when you press on the "Data Station" button in Plan View

### ISSUE THREAD

**Issue by dbcarelli** [dbcarelli/qgroundcontrol-mission-mule#8]
To be clear, NOT the place data station button. Instead, once a data station is placed, if you select it and press where is says "Data Station", the app crashes.

**Comment by mounir-khaled** [comment]
This was fixed right?

**Comment by dbcarelli** [comment]
Still a problem, but it also happens with other buttons. This seems to be a QGC-wide bug.
